import type { GotongProject, MemberId } from "@/lib/gotong-types";

export const sampleNotes =
  "Nigel will handle the pitch and product story. Aisha is doing frontend. Wei Jian is checking Chutes API and auth. Priya is working on the Web3 proof layer. We need a demo by Thursday. Frontend is blocked because the API format is not finalized. Pitch needs screenshots. Web3 proof can be mocked first.";

export const baseGotongProject: GotongProject = {
  goal: "AI + Web3 productivity demo by Thursday",
  deadline: "Thursday demo",
  sourceNotes: sampleNotes,
  members: [
    {
      id: "nigel",
      name: "Nigel",
      initials: "N",
      role: "Story",
      focus: "Pitch + product arc",
      color: "#f6b84b",
      ring: "#ffe0a1",
      x: 185,
      y: 170,
    },
    {
      id: "aisha",
      name: "Aisha",
      initials: "A",
      role: "Frontend",
      focus: "Interactive MVP",
      color: "#35c7b3",
      ring: "#9ff6ea",
      x: 190,
      y: 455,
    },
    {
      id: "wei-jian",
      name: "Wei Jian",
      initials: "WJ",
      role: "Chutes",
      focus: "API + auth",
      color: "#6d8cff",
      ring: "#c8d4ff",
      x: 815,
      y: 175,
    },
    {
      id: "priya",
      name: "Priya",
      initials: "P",
      role: "Web3",
      focus: "Proof layer",
      color: "#e85d87",
      ring: "#ffc2d4",
      x: 810,
      y: 455,
    },
  ],
  tasks: [
    {
      id: "pitch-story",
      title: "Pitch Story",
      ownerId: "nigel",
      status: "pending",
      tag: "Narrative",
      shortStatus: "Needs screenshots",
      dependencyIds: ["frontend-demo"],
      blocker: "Waiting for fresh demo shots",
      nextMove: "Capture map + proof moments",
      x: 405,
      y: 105,
    },
    {
      id: "frontend-demo",
      title: "Frontend Demo",
      ownerId: "aisha",
      status: "blocked",
      tag: "Build",
      shortStatus: "Blocked",
      dependencyIds: ["chutes-api"],
      blocker: "API format not finalized",
      nextMove: "Use mock schema now",
      x: 410,
      y: 365,
    },
    {
      id: "chutes-api",
      title: "Chutes API + Auth",
      ownerId: "wei-jian",
      status: "pending",
      tag: "AI/Auth",
      shortStatus: "Define schema",
      dependencyIds: [],
      nextMove: "Freeze response JSON",
      x: 590,
      y: 235,
    },
    {
      id: "web3-proof",
      title: "Web3 Proof Layer",
      ownerId: "priya",
      status: "pending",
      tag: "Proof",
      shortStatus: "Mock first",
      dependencyIds: [],
      nextMove: "Anchor report hash",
      x: 585,
      y: 515,
    },
  ],
  edges: [
    {
      id: "owner-nigel-pitch",
      from: "nigel",
      to: "pitch-story",
      label: "owns",
      tone: "owner",
    },
    {
      id: "owner-aisha-frontend",
      from: "aisha",
      to: "frontend-demo",
      label: "owns",
      tone: "blocked",
    },
    {
      id: "owner-wei-chutes",
      from: "wei-jian",
      to: "chutes-api",
      label: "owns",
      tone: "owner",
    },
    {
      id: "owner-priya-proof",
      from: "priya",
      to: "web3-proof",
      label: "owns",
      tone: "owner",
    },
    {
      id: "dep-api-frontend",
      from: "chutes-api",
      to: "frontend-demo",
      label: "unblocks",
      tone: "blocked",
    },
    {
      id: "dep-frontend-pitch",
      from: "frontend-demo",
      to: "pitch-story",
      label: "screens",
      tone: "dependency",
    },
  ],
  blockedTaskIds: ["frontend-demo"],
  nextAction: "Freeze Chutes JSON, then unblock Aisha.",
  fairnessInsight: "Work is balanced; one blocker hides Aisha's effort.",
  contributionBalance: [
    { memberId: "nigel", completed: 0, pending: 1, blocked: 0 },
    { memberId: "aisha", completed: 0, pending: 0, blocked: 1 },
    { memberId: "wei-jian", completed: 0, pending: 1, blocked: 0 },
    { memberId: "priya", completed: 0, pending: 1, blocked: 0 },
  ],
};

export function getMemberName(project: GotongProject, id: MemberId) {
  return project.members.find((member) => member.id === id)?.name ?? "Team";
}
